<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" IncludeAssets="compile" />
		<PackageReference Include="Microsoft.CodeAnalysis.ResxSourceGenerator" PrivateAssets="all" />
		<PackageReference Include="SteamKit2" IncludeAssets="compile" />
		<PackageReference Include="System.Composition.AttributedModel" IncludeAssets="compile" />
		<ProjectReference Include="../ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj" ExcludeAssets="all" Private="false" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Localization/Strings.resx" EmitFormatMethods="true" />
	</ItemGroup>
</Project>
